export const GET_COMICS = {
  LOAD: 'MAIN_HOME/GET_COMICS_LOAD',
  LOAD_MORE: 'MAIN_HOME/GET_COMICS_LOAD_MORE',
  LOAD_MORE_SUCCESS: 'MAIN_HOME/GET_COMICS_LOAD_MORE_SUCCESS',
  LOAD_MORE_FAILURE: 'MAIN_HOME/GET_COMICS_LOAD_MORE_FAILURE',
  SUCCESS: 'MAIN_HOME/GET_COMICS_SUCCESS',
  FAILURE: 'MAIN_HOME/GET_COMICS_FAILURE',
};

export const STORE_COMICS = {
  STORE: 'MAIN_HOME/STORE_COMICS_STORE',
  RESET: 'MAIN_HOME/STORE_COMICS_RESET',
};
